//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ImageProcessEx.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_IMAGEPTYPE                  129
#define IDD_DIALOG_RAWTOBMP             130
#define IDD_DIALOG_LINEARTRANS          131
#define IDD_DIALOG_HISTOEQUIVALIZE      132
#define IDD_DIALOG_LOWPASS              133
#define IDD_DIALOG_HIGHPASS             134
#define IDD_DIALOG_MIDDLEPASS           135
#define IDD_DIALOG_TRANSLATION          136
#define IDD_DIALOG_ZOOM                 137
#define IDD_DIALOG_ROTATE               138
#define IDD_DIALOG_TRANSPOSE            139
#define IDD_DIALOG_FOURIE               140
#define IDD_DIALOG_IFOURIE              141
#define IDD_DIALOG_BWLOWPASS            142
#define IDD_DIALOG_BWHIGHPASS           143
#define IDD_DIALOG_ROBERTS              144
#define IDD_DIALOG_PREWITT              145
#define IDD_DIALOG_SOBEL                146
#define IDC_EDIT_RAWCIN                 1000
#define IDC_BUTTON_RAWVIEW              1003
#define IDC_EDIT_BMPCIN                 1004
#define IDC_BUTTON_BMPVIEW              1005
#define IDC_EDIT_WIDTHCIN               1006
#define IDC_EDIT_HEIGHTCIN              1007
#define IDC_STATIC_RAWFILE              1008
#define IDC_STATIC_BMPFILE              1009
#define IDC_STATIC_RAWPARAM             1010
#define IDC_STATIC_WIDTH                1011
#define IDC_STATIC_HEIGHT               1012
#define IDC_STATIC_GRAYORBGR            1013
#define IDC_STATIC_FORMAT               1014
#define IDC_RADIO_GRAY                  1015
#define IDC_RADIO_BGR                   1016
#define IDC_RADIO_BSQ                   1017
#define IDC_RADIO_BIP                   1018
#define IDC_RADIO_BIL                   1019
#define IDC_EDIT_LINEARINPUT            1020
#define IDC_BUTTON_LINEARINPUT          1021
#define IDC_STATIC_LINEARINPUT          1022
#define IDC_STATIC_LINEAROUTPUT         1023
#define IDC_EDIT_HISTOIN                1023
#define IDC_EDIT_LINEAROUTPUT           1024
#define IDC_BUTTON_HISTOINPUT           1024
#define IDC_BUTTON_LINEAROUTPUT         1025
#define IDC_STATIC_HISTOIN              1025
#define IDC_STATIC_HISTOOUT             1026
#define IDC_EDIT_HISTOOUT               1027
#define IDC_BUTTON_HISTOOUTPUT          1028
#define IDC_EDIT_LOWPASSIN              1030
#define IDC_BUTTON_LOWPASSIN            1031
#define IDC_STATIC_LOWPASSIN            1032
#define IDC_STATIC_LOWPASSOUT           1033
#define IDC_EDIT_HIGHPASSIN             1033
#define IDC_EDIT_LOWPASSOUT             1034
#define IDC_BUTTON_HIGHPASSIN           1034
#define IDC_BUTTON_LOWPASSOUT           1035
#define IDC_STATIC_HIGHPASSIN           1035
#define IDC_STATIC_HIGHPASSOUT          1036
#define IDC_EDIT_MIDDLEPASSIN           1036
#define IDC_EDIT_HIGHPASSOUT            1037
#define IDC_BUTTON_MIDDLEPASSIN         1037
#define IDC_BUTTON_HIGHPASSOUT          1038
#define IDC_STATIC_MIDDLEPASSIN         1038
#define IDC_STATIC_MIDDLEPASSOUT        1039
#define IDC_EDIT_TRANSLATIONIN          1039
#define IDC_EDIT_MIDDLEPASSOUT          1040
#define IDC_BUTTON_TRANSLATIONIN        1040
#define IDC_BUTTON_MIDDLEPASSOUT        1041
#define IDC_STATIC_TRANSLATIONIN        1041
#define IDC_STATIC_TRANSLATIONOUT       1042
#define IDC_EDIT_TRANSLATIONOUT         1043
#define IDC_BUTTON_TRANSLATIONOUT       1044
#define IDC_EDIT_DIRECTX                1045
#define IDC_STATIC_DIRECTX              1046
#define IDC_STATIC_DIRECTY              1047
#define IDC_EDIT_ZOOMIN                 1048
#define IDC_EDIT_DIRECTY                1049
#define IDC_BUTTON_ZOOMIN               1049
#define IDC_STATIC_ZOOMIN               1050
#define IDC_STATIC_ZOOMOUT              1051
#define IDC_EDIT_ZOOMOUT                1052
#define IDC_BUTTON_ZOOMOUT              1053
#define IDC_EDIT_XZOOMRATIO             1054
#define IDC_STATIC_XZOOMRATIO           1055
#define IDC_EDIT_ROTATEIN               1056
#define IDC_BUTTON_ROTATEIN             1057
#define IDC_STATIC_YZOOMRATIO           1058
#define IDC_STATIC_ROTATEIN             1058
#define IDC_EDIT_YZOOMRATIO             1059
#define IDC_STATIC_ROTATEOUT            1059
#define IDC_EDIT_ROTATEOUT              1060
#define IDC_BUTTON_ROTATEOUT            1061
#define IDC_EDIT_ROTATEANGEL            1062
#define IDC_STATIC_ROTATEANGEL          1063
#define IDC_EDIT_TRANSPOSEIN            1064
#define IDC_BUTTON_TRANSPOSEIN          1065
#define IDC_STATIC_TRANSPOSEIN          1066
#define IDC_STATIC_TRANSPOSEOUT         1067
#define IDC_EDIT_FOURIEIN               1067
#define IDC_EDIT_TRANSPOSEOUT           1068
#define IDC_BUTTON_FOURIEIN             1068
#define IDC_BUTTON_TRANSPOSEOUT         1069
#define IDC_STATIC_FOURIEIN             1069
#define IDC_STATIC_FOURIEOUT            1070
#define IDC_EDIT_FOURIEOUT              1071
#define IDC_BUTTON_IFOURIEIN            1071
#define IDC_BUTTON_FOURIEOUT            1072
#define IDC_STATIC_IFOURIEIN            1072
#define IDC_EDIT_IFOURIEIN              1073
#define IDC_STATIC_IFOURIEOUT           1074
#define IDC_STATIC_BWLOWPASSIN          1074
#define IDC_EDIT_IFOURIEOUT             1075
#define IDC_EDIT_BWLOWPASSIN            1075
#define IDC_BUTTON_IFOURIEOUT           1076
#define IDC_BUTTON_BWLOWPASSIN          1076
#define IDC_STATIC_BWLOWPASSOUT         1077
#define IDC_EDIT_BWLOWPASSOUT           1078
#define IDC_BUTTON_BWLOWPASSOUT         1079
#define IDC_STATIC_BWHIGHPASSIN         1080
#define IDC_EDIT_BWHIGHPASSIN           1081
#define IDC_BUTTON_BWHIGHPASSIN         1082
#define IDC_STATIC_BWHIGHPASSOUT        1083
#define IDC_EDIT_BWHIGHPASSOUT          1084
#define IDC_BUTTON_BWHIGHPASSOUT        1085
#define IDC_STATIC_ROBERTSIN            1086
#define IDC_EDIT_ROBERTSIN              1087
#define IDC_BUTTON_ROBERTSIN            1088
#define IDC_STATIC_ROBERTSOUT           1089
#define IDC_EDIT_ROBERTSSOUT            1090
#define IDC_BUTTON_ROBERTSOUT           1091
#define IDC_STATIC_PREWITTIN            1092
#define IDC_EDIT_PREWITTIN              1093
#define IDC_BUTTON_PREWITTIN            1094
#define IDC_STATIC_PREWITTOUT           1095
#define IDC_EDIT_PREWITTOUT             1096
#define IDC_BUTTON_PREWITTOUT           1097
#define IDC_STATIC_SOBELIN              1098
#define IDC_EDIT_SOBELIN                1099
#define IDC_BUTTON_SOBELIN              1100
#define IDC_STATIC_SOBELOUT             1101
#define IDC_EDIT_SOBELOUT               1102
#define IDC_BUTTON_SOBELOUT             1103
#define ID_RAWTOBMP                     32771
#define ID_LINEARENHENCE                32772
#define ID_HISTOEQUIVALIZE              32773
#define ID_LOWPASS                      32775
#define ID_HIGHPASS                     32776
#define ID_MIDDLEPASS                   32777
#define ID_TRANSLATION                  32778
#define ID_ZOOM                         32779
#define ID_ROTATE                       32780
#define ID_TRANSPOSITION                32781
#define ID_FOURIE                       32782
#define ID_IFOURIE                      32783
#define ID_BWLOWPASS                    32784
#define ID_BWHIGHPASS                   32785
#define ID_ROBERTS                      32786
#define ID_PREWITT                      32787
#define ID_SOBEL                        32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
